// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'column-title'
  | 'internal-error'
  | 'itemmenu-retrieve-api'
  | 'itemmenu-retrieve-title'
  | 'menutools-autoretrieve-api'
  | 'menutools-autoretrieve-api-none'
  | 'menutools-autoretrieve-title'
  | 'preference-pane-label'
  | 'preferences-pane-autoretrieve-api'
  | 'preferences-pane-autoretrieve-api-none'
  | 'preferences-pane-autoretrieve-title'
  | 'preferences-pane-scopus-api-key-input'
  | 'preferences-pane-scopus-api-key-title'
  | 'progresswindow-error-bad-api-response'
  | 'progresswindow-error-no-arxiv'
  | 'progresswindow-error-no-citation-count'
  | 'progresswindow-error-no-doi'
  | 'progresswindow-error-no-doi-or-arxiv'
  | 'progresswindow-error-no-scopus-api-key'
  | 'progresswindow-finished-headline'
  | 'progresswindow-headline';
